In [66]:
import pandas as pd
import numpy as np

In [67]:
import sys
# Prints the absolute path of the executable binary
print("Interpreter Path:", sys.executable)

# Prints the detailed version info
print("Python Version:", sys.version)

Interpreter Path: c:\Users\User\Desktop\ETAI\ETAI-Pipeline\venv\Scripts\python.exe
Python Version: 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]

In [68]:
df = pd.read_csv('../data/compas_two_year_recidivism.csv')

In [69]:
df.tail(20)

,juv_other_count,score_text,priors_count,juv_misd_count,juvenile_total,sex,age_cat,id,c_charge_degree,two_year_recid,juv_fel_count,age_in_months,race,prior_offenses,age,decile_score
7266,0,Low,4.0,0,0.0,Female,25 - 45,9280,M,0,0.0,408.0,Caucasian,4.0,34.0,4
7267,0,Medium,1.0,0,1.0,Male,Less than 25,5203,F,1,1.0,240.0,African-American,1.0,20.0,7
7268,0,Low,1.0,0,0.0,Male,25 - 45,3039,F,1,0.0,420.0,Caucasian,1.0,35.0,1
7269,0,High,9.0,0,0.0,Male,25 - 45,8638,F,1,0.0,372.0,African-American,9.0,31.0,8
7270,0,Low,NaN,0,0.0,Male,Greater than 45,6776,F,0,0.0,660.0,Caucasian,NaN,55.0,3
7271,0,Low,11.0,0,0.0,Male,25 - 45,869,M,0,0.0,528.0,Caucasian,11.0,44.0,3
7272,0,Low,1.0,0,0.0,Male,25 - 45,120,M,0,0.0,492.0,African-American,1.0,41.0,2
7273,0,Low,3.0,0,0.0,Male,Greater than 45,4993,F,0,0.0,624.0,Hispanic,3.0,52.0,4
7274,0,High,5.0,3,3.0,Male,Less than 25,2301,F,1,0.0,276.0,African-American,5.0,23.0,9
7275,0,Medium,6.0,0,0.0,Male,25 - 45,2317,f,1,0.0,324.0,African-American,6.0,27.0,5
7276,0,Low,0.0,0,0.0,Male,Greater than 45,3096,F,0,0.0,720.0,African American,0.0,60.0,1
7277,0,Low,0.0,0,0.0,Male,25 - 45,7012,F,0,0.0,336.0,African-American,0.0,28.0,2
7278,0,Low,0.0,0,0.0,Female,25 - 45,6934,F,0,0.0,396.0,African-American,0.0,33.0,3
7279,1,High,2.0,2,3.0,Male,Less than 25,9017,F,1,0.0,240.0,Hispanic,2.0,20.0,8
7280,0,LOW,0.0,0,0.0,Female,Greater than 45,3884,F,1,0.0,648.0,Caucasian,0.0,54.0,3
7281,0,Medium,0.0,0,0.0,Male,Less than 25,1685,f,1,0.0,288.0,Hispanic,0.0,24.0,6
7282,0,Low,3.0,0,0.0,Male,25 - 45,616,F,0,0.0,384.0,African-American,3.0,32.0,2
7283,0,Low,3.0,0,0.0,Male,Greater than 45,5394,F,0,0.0,672.0,-,3.0,56.0,2
7284,0,Low,1.0,0,0.0,Male,25 - 45,2422,F,0,0.0,324.0,African-American,1.0,27.0,2
7285,0,Medium,0.0,0,0.0,Male,Less than 25,8606,NaN,1,0.0,288.0,African-American,0.0,24.0,7

## Exploration

In [70]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7286 entries, 0 to 7285
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   juv_other_count  7286 non-null   int64
 1   score_text       7286 non-null   str
 2   priors_count     6866 non-null   str
 3   juv_misd_count   7286 non-null   int64
 4   juvenile_total   7286 non-null   float64
 5   sex              7226 non-null   str
 6   age_cat          7286 non-null   str
 7   id               7286 non-null   int64
 8   c_charge_degree  7053 non-null   str
 9   two_year_recid   7286 non-null   int64
 10  juv_fel_count    7069 non-null   float64
 11  age_in_months    7140 non-null   float64
 12  race             7286 non-null   str
 13  prior_offenses   6866 non-null   str
 14  age              7140 non-null   float64
 15  decile_score     7286 non-null   int64
dtypes: float64(4), int64(5), str(7)
memory usage: 910.9 KB

In [71]:
for col in df.columns:
    print(col, sum(df[col].isnull()))

juv_other_count 0
score_text 0
priors_count 420
juv_misd_count 0
juvenile_total 0
sex 60
age_cat 0
id 0
c_charge_degree 233
two_year_recid 0
juv_fel_count 217
age_in_months 146
race 0
prior_offenses 420
age 146
decile_score 0

In [72]:
df.describe()

,juv_other_count,juv_misd_count,juvenile_total,id,two_year_recid,juv_fel_count,age_in_months,age,decile_score
count,7286.000000,7286.000000,7286.000000,7286.000000,7286.000000,7069.000000,7140.000000,7140.000000,7286.000000
mean,0.109662,0.090585,0.265852,5499.579193,0.451139,0.067619,417.203361,34.766947,4.524156
std,0.502209,0.483668,0.950096,3174.414353,0.497641,0.478998,143.352811,11.946068,2.877104
min,0.000000,0.000000,-1.000000,1.000000,0.000000,-1.000000,-36.000000,-3.000000,0.000000
25%,0.000000,0.000000,0.000000,2736.250000,0.000000,0.000000,300.000000,25.000000,2.000000
50%,0.000000,0.000000,0.000000,5507.500000,0.000000,0.000000,372.000000,31.000000,4.000000
75%,0.000000,0.000000,0.000000,8238.500000,1.000000,0.000000,504.000000,42.000000,7.000000
max,17.000000,13.000000,21.000000,11001.000000,1.000000,20.000000,1152.000000,96.000000,23.000000

In [73]:
categorical_columns = df.select_dtypes(include=["object", "category", "str"]).columns
print(categorical_columns)

Index(['score_text', 'priors_count', 'sex', 'age_cat', 'c_charge_degree',
       'race', 'prior_offenses'],
      dtype='str')

In [74]:
for col in df.select_dtypes(include=["object", "category", "str"]).columns:
    print(col, df[col].unique())

score_text <StringArray>
['Low', 'High', 'Medium', 'low', 'medium', 'LOW', 'MEDIUM', 'HIGH', 'high']
Length: 9, dtype: str
priors_count <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
    '-',  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0',
 '17.0', '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0',
 '38.0', '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0',
 '30.0', '35.0', '36.0', '37.0',  '500']
Length: 41, dtype: str
sex <StringArray>
[   'Male',    'male',  'female',  'Female',    'MALE',   ' Male', 'Female ',
       nan,       '?',  'FEMALE']
Length: 10, dtype: str
age_cat <StringArray>
['25 - 45', 'Less than 25', 'Greater than 45']
Length: 3, dtype: str
c_charge_degree <StringArray>
['F', 'M', 'm', 'Misdemeanor', nan, 'Felony', 'f']
Length: 7, dtype: str
race <StringArray>
[ 'African-American',         'Caucasian',                 '?',
          'Hispanic',             'Other',  'african-american',
 ' African-American',          'HISPANIC',         'caucasian',
                 '-',          'hispanic',         'CAUCASIAN',
   'Native American',        ' Caucasian',  'African American',
  'AFRICAN-AMERICAN',             'Asian']
Length: 17, dtype: str
prior_offenses <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
    '-',  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0',
 '17.0', '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0',
 '38.0', '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0',
 '30.0', '35.0', '36.0', '37.0',  '500']
Length: 41, dtype: str

# Prepocessing steps needed:
1. Missing values like '?', '-'
2. Different names for the same category 
3. Numerical values like strings
4. Negative values in numerical columns
5. Range of numerical values
6. Duplicate values
7. id column

In [75]:
def standardize_missing_values(df, missing_values_types = ['?', '-'] ):
    for col in df.select_dtypes(include=["object", "category", "str"]).columns:
        df[col] = df[col].replace(missing_values_types, np.nan)
    return df

In [76]:
df = standardize_missing_values(df)

In [77]:
for col in df.select_dtypes(include=["object", "category", "str"]).columns:
    print(col, df[col].unique())

score_text <StringArray>
['Low', 'High', 'Medium', 'low', 'medium', 'LOW', 'MEDIUM', 'HIGH', 'high']
Length: 9, dtype: str
priors_count <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0', '17.0',
 '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0', '38.0',
 '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0', '30.0',
 '35.0', '36.0', '37.0',  '500']
Length: 40, dtype: str
sex <StringArray>
['Male', 'male', 'female', 'Female', 'MALE', ' Male', 'Female ', nan,
 'FEMALE']
Length: 9, dtype: str
age_cat <StringArray>
['25 - 45', 'Less than 25', 'Greater than 45']
Length: 3, dtype: str
c_charge_degree <StringArray>
['F', 'M', 'm', 'Misdemeanor', nan, 'Felony', 'f']
Length: 7, dtype: str
race <StringArray>
[ 'African-American',         'Caucasian',                 nan,
          'Hispanic',             'Other',  'african-american',
 ' African-American',          'HISPANIC',         'caucasian',
          'hispanic',         'CAUCASIAN',   'Native American',
        ' Caucasian',  'African American',  'AFRICAN-AMERICAN',
             'Asian']
Length: 16, dtype: str
prior_offenses <StringArray>
[ '0.0',  '3.0',  '2.0',  '1.0',    nan, '18.0', '16.0',  '6.0',  '7.0',
  '4.0',  '9.0', '19.0',  '5.0', '10.0', '13.0',  '8.0', '14.0', '17.0',
 '11.0', '24.0', '25.0', '15.0', '12.0', '23.0', '33.0', '20.0', '38.0',
 '28.0',  '250', '26.0', '21.0', '22.0', '29.0', '27.0', '31.0', '30.0',
 '35.0', '36.0', '37.0',  '500']
Length: 40, dtype: str

In [78]:
def transform_cat_to_num(df, cols = ["prior_offenses", "priors_count"]):
    for col in cols:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        # errors='coerce' turn non-numeric strings into NaN 
    return df

In [79]:
df = transform_cat_to_num(df)

In [80]:
df.select_dtypes('number')

,juv_other_count,priors_count,juv_misd_count,juvenile_total,id,two_year_recid,juv_fel_count,age_in_months,prior_offenses,age,decile_score
0,1,0.0,0,1.0,8423,0,0.0,324.0,0.0,27.0,2
1,0,3.0,0,0.0,4137,1,0.0,276.0,3.0,23.0,8
2,0,2.0,0,0.0,5064,1,0.0,336.0,2.0,28.0,2
3,0,2.0,0,0.0,56,0,NaN,252.0,2.0,21.0,8
4,0,1.0,0,0.0,9369,0,0.0,372.0,1.0,31.0,4
...,...,...,...,...,...,...,...,...,...,...,...
7281,0,0.0,0,0.0,1685,1,0.0,288.0,0.0,24.0,6
7282,0,3.0,0,0.0,616,0,0.0,384.0,3.0,32.0,2
7283,0,3.0,0,0.0,5394,0,0.0,672.0,3.0,56.0,2
7284,0,1.0,0,0.0,2422,0,0.0,324.0,1.0,27.0,2
7285,0,0.0,0,0.0,8606,1,0.0,288.0,0.0,24.0,7

In [81]:
# `Male`, `Female`
# `African-American`, `Caucasian`, `Hispanic`, `Asian`, `Native American`, `Other`
# `Low`, `Medium`, `High`
# `F`, `M`

In [82]:
def change_categorical_col(df, cat_cols = ["score_text", "sex", "c_charge_degree", "race",]):
    #['Low', 'High', 'Medium', 'low', 'medium', 'LOW', 'MEDIUM', 'HIGH', 'high']
    map_score = {'low': 'Low', 'medium': 'Medium', 'high': 'High'}
    #['Male', 'male', 'female', 'Female', 'MALE', ' Male', 'Female ', nan, 'FEMALE']
    map_sex = {'male': 'Male', 'female': 'Female'}
    #['F', 'M', 'm', 'Misdemeanor', nan, 'Felony', 'f']
    map_charge_degree= {'m': 'M', 'f': 'F', 'misdemeanor': 'M', 'felony': 'F'} 
    #[ 'African-American','Caucasian', nan, 'Hispanic','Other',  'african-american',' African-American', 'HISPANIC','caucasian',
    # 'hispanic', 'CAUCASIAN','Native America', Caucasian',  'African American',  'AFRICAN-AMERICAN', 'Asian']
    map_race = {'african-american': 'African-American', 'caucasian': 'Caucasian', 'hispanic': 'Hispanic',
                'asian': 'Asian', 'other': 'Other', 'native american': 'Native American', 'african american': 'African-American' }
    df["score_text"] = df["score_text"].str.lower().str.strip().map(map_score)
    df["sex"] = df["sex"].str.lower().str.strip().map(map_sex)
    df["c_charge_degree"] = df["c_charge_degree"].str.lower().str.strip().map(map_charge_degree)
    df["race"] = df["race"].str.lower().str.strip().map(map_race)
    return df

In [83]:
df1 = change_categorical_col(df)

In [84]:
for col in df.select_dtypes(include=["object", "category", "str"]).columns:
    print(col, df[col].unique())

score_text <StringArray>
['Low', 'High', 'Medium']
Length: 3, dtype: str
sex <StringArray>
['Male', 'Female', nan]
Length: 3, dtype: str
age_cat <StringArray>
['25 - 45', 'Less than 25', 'Greater than 45']
Length: 3, dtype: str
c_charge_degree <StringArray>
['F', 'M', nan]
Length: 3, dtype: str
race <StringArray>
['African-American',        'Caucasian',                nan,
         'Hispanic',            'Other',  'Native American',
            'Asian']
Length: 7, dtype: str

In [85]:
df.count()

juv_other_count    7286
score_text         7286
priors_count       6785
juv_misd_count     7286
juvenile_total     7286
sex                7177
age_cat            7286
id                 7286
c_charge_degree    7053
two_year_recid     7286
juv_fel_count      7069
age_in_months      7140
race               7142
prior_offenses     6785
age                7140
decile_score       7286
dtype: int64

In [86]:
for col in df.select_dtypes('number'):
    print(col, df[col].min(), df[col].max())

juv_other_count 0 17
priors_count 0.0 500.0
juv_misd_count 0 13
juvenile_total -1.0 21.0
id 1 11001
two_year_recid 0 1
juv_fel_count -1.0 20.0
age_in_months -36.0 1152.0
prior_offenses 0.0 500.0
age -3.0 96.0
decile_score 0 23

In [89]:
df = df[['id', 'sex', 'age', 'age_in_months','age_cat', 'juv_misd_count', 'juv_fel_count', 'juv_other_count', 'juvenile_total','prior_offenses', 'priors_count','race', 'c_charge_degree', 'two_year_recid', 'score_text', 'decile_score']]

In [93]:
df[df['juvenile_total'] != 0.0]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
0,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
6,967,Male,27.0,324.0,25 - 45,2,0.0,1,3.0,18.0,18.0,African-American,F,1,High,9
32,2138,Male,34.0,408.0,25 - 45,2,0.0,1,3.0,19.0,19.0,African-American,F,1,High,10
34,9240,Male,27.0,324.0,25 - 45,0,1.0,0,1.0,1.0,1.0,African-American,F,1,Medium,5
47,2247,Male,31.0,372.0,25 - 45,0,3.0,0,3.0,6.0,6.0,African-American,F,1,High,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7249,51,Male,26.0,312.0,25 - 45,0,0.0,2,2.0,6.0,6.0,Caucasian,M,0,High,8
7253,3268,Male,25.0,300.0,25 - 45,2,0.0,0,2.0,5.0,5.0,Caucasian,M,1,Medium,7
7267,5203,Male,20.0,240.0,Less than 25,0,1.0,0,1.0,1.0,1.0,African-American,F,1,Medium,7
7274,2301,Male,23.0,276.0,Less than 25,3,0.0,0,3.0,5.0,5.0,African-American,F,1,High,9
7279,9017,Male,20.0,240.0,Less than 25,2,0.0,1,3.0,2.0,2.0,Hispanic,F,1,High,8

In [96]:
df[df['juv_fel_count'] < 0.0]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
1379,7053,Male,36.0,432.0,25 - 45,0,-1.0,0,-1.0,0.0,0.0,African-American,F,0,Low,4
2351,1810,Male,30.0,360.0,25 - 45,0,-1.0,0,-1.0,0.0,0.0,Hispanic,M,0,Low,1
2653,2442,Male,24.0,288.0,Less than 25,2,-1.0,1,2.0,NaN,NaN,African-American,F,1,High,9
4821,6337,Male,51.0,612.0,Greater than 45,0,-1.0,0,-1.0,14.0,14.0,African-American,F,0,Medium,5
5792,522,Male,37.0,444.0,25 - 45,0,-1.0,0,-1.0,0.0,0.0,Caucasian,F,0,Low,1

In [98]:
df[df['age']<= 0.0]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
2307,2060,Male,-3.0,-36.0,25 - 45,0,0.0,0,0.0,3.0,3.0,African-American,F,1,Medium,5
2365,5390,Male,-3.0,-36.0,Less than 25,0,0.0,0,0.0,NaN,NaN,African-American,F,1,High,9
3546,3023,Male,-3.0,-36.0,25 - 45,1,0.0,0,1.0,14.0,14.0,African-American,F,1,High,9
4123,2060,Male,-3.0,-36.0,25 - 45,0,0.0,0,0.0,3.0,3.0,African-American,F,1,Medium,5
4815,2828,Female,-3.0,-36.0,Less than 25,0,0.0,0,0.0,0.0,0.0,African-American,NaN,1,Medium,7

In [103]:
df[(df['decile_score']>10) | (df['decile_score'] < 1)]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
20,5096,Female,38.0,456.0,25 - 45,0,0.0,0,0.0,0.0,0.0,African-American,M,0,Low,15
567,9129,Male,26.0,312.0,25 - 45,0,0.0,0,0.0,2.0,2.0,African-American,F,0,Medium,23
2321,9238,Female,34.0,408.0,25 - 45,0,0.0,0,0.0,0.0,0.0,African-American,F,0,Low,0
4319,9088,Male,45.0,540.0,Greater than 45,0,0.0,0,0.0,2.0,2.0,Caucasian,F,0,Low,0
4971,2363,Male,41.0,492.0,25 - 45,0,0.0,0,0.0,5.0,5.0,Caucasian,F,0,Low,23
5650,916,Male,40.0,480.0,25 - 45,0,0.0,0,0.0,0.0,0.0,African-American,F,0,Low,15

In [104]:
def clean_numerical_cols(df, num_cols = ['juvenile_total', 'juv_fel_count', 'age_in_months', 'age']):
    df.loc[df['age'] < 0, 'age'] = np.nan
    df.loc[df['age_in_months']<0, 'age_in_months']= np.nan
    df.loc[df['juv_fel_count']<0, 'juv_fel_count']= np.nan
    df.loc[df['juvenile_total']<0, 'juvenile_total']= np.nan
    return df

In [105]:
df = clean_numerical_cols(df)
df

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
0,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
1,4137,Male,23.0,276.0,Less than 25,0,0.0,0,0.0,3.0,3.0,Caucasian,M,1,High,8
2,5064,Male,28.0,336.0,25 - 45,0,0.0,0,0.0,2.0,2.0,Caucasian,F,1,Low,2
3,56,Female,21.0,252.0,Less than 25,0,NaN,0,0.0,2.0,2.0,African-American,F,0,High,8
4,9369,Male,31.0,372.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,M,0,Low,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,1685,Male,24.0,288.0,Less than 25,0,0.0,0,0.0,0.0,0.0,Hispanic,F,1,Medium,6
7282,616,Male,32.0,384.0,25 - 45,0,0.0,0,0.0,3.0,3.0,African-American,F,0,Low,2
7283,5394,Male,56.0,672.0,Greater than 45,0,0.0,0,0.0,3.0,3.0,NaN,F,0,Low,2
7284,2422,Male,27.0,324.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,F,0,Low,2
7285,8606,Male,24.0,288.0,Less than 25,0,0.0,0,0.0,0.0,0.0,African-American,NaN,1,Medium,7

In [109]:
df.isna().sum()

id                   0
sex                109
age                151
age_in_months      151
age_cat              0
juv_misd_count       0
juv_fel_count      222
juv_other_count      0
juvenile_total       4
prior_offenses     501
priors_count       501
race               144
c_charge_degree    233
two_year_recid       0
score_text           0
decile_score         0
dtype: int64

In [110]:
df[df['id']>7286]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
0,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
4,9369,Male,31.0,372.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,M,0,Low,4
5,7663,Female,51.0,612.0,Greater than 45,0,0.0,0,0.0,NaN,NaN,Caucasian,F,0,Low,1
8,10296,Male,40.0,480.0,25 - 45,0,0.0,0,0.0,1.0,1.0,NaN,F,0,Low,3
10,10873,Female,28.0,336.0,25 - 45,0,0.0,0,0.0,6.0,6.0,African-American,M,1,Medium,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7265,10361,Female,26.0,312.0,25 - 45,0,NaN,0,0.0,1.0,1.0,Caucasian,F,0,High,9
7266,9280,Female,34.0,408.0,25 - 45,0,0.0,0,0.0,4.0,4.0,Caucasian,M,0,Low,4
7269,8638,Male,31.0,372.0,25 - 45,0,0.0,0,0.0,9.0,9.0,African-American,F,1,High,8
7279,9017,Male,20.0,240.0,Less than 25,2,0.0,1,3.0,2.0,2.0,Hispanic,F,1,High,8
7285,8606,Male,24.0,288.0,Less than 25,0,0.0,0,0.0,0.0,0.0,African-American,NaN,1,Medium,7

In [112]:
df.duplicated().sum()

np.int64(72)

In [113]:
df[df.duplicated()]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
1719,6852,Male,27.0,324.0,25 - 45,0,0.0,0,0.0,0.0,0.0,Other,F,1,Low,2
1768,5009,Female,29.0,348.0,25 - 45,0,0.0,0,0.0,0.0,0.0,Caucasian,M,0,Low,2
1805,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
1882,8105,Male,21.0,252.0,Less than 25,2,0.0,1,3.0,3.0,3.0,African-American,NaN,1,High,9
2115,4262,Male,25.0,300.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,F,1,Low,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7081,9327,NaN,22.0,264.0,Less than 25,0,0.0,0,0.0,1.0,1.0,African-American,NaN,1,High,9
7108,5491,Male,20.0,240.0,Less than 25,0,0.0,0,0.0,0.0,0.0,Caucasian,F,0,Low,4
7150,9561,Male,28.0,336.0,25 - 45,0,0.0,0,0.0,3.0,3.0,Caucasian,F,1,Medium,7
7174,10586,Male,47.0,564.0,Greater than 45,0,0.0,0,0.0,3.0,3.0,African-American,M,1,Medium,5
7200,1665,Male,34.0,408.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,M,0,Medium,6

In [114]:
df['id'].duplicated().sum()

np.int64(72)

In [115]:
df[df['id'].duplicated()]

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
1719,6852,Male,27.0,324.0,25 - 45,0,0.0,0,0.0,0.0,0.0,Other,F,1,Low,2
1768,5009,Female,29.0,348.0,25 - 45,0,0.0,0,0.0,0.0,0.0,Caucasian,M,0,Low,2
1805,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
1882,8105,Male,21.0,252.0,Less than 25,2,0.0,1,3.0,3.0,3.0,African-American,NaN,1,High,9
2115,4262,Male,25.0,300.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,F,1,Low,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7081,9327,NaN,22.0,264.0,Less than 25,0,0.0,0,0.0,1.0,1.0,African-American,NaN,1,High,9
7108,5491,Male,20.0,240.0,Less than 25,0,0.0,0,0.0,0.0,0.0,Caucasian,F,0,Low,4
7150,9561,Male,28.0,336.0,25 - 45,0,0.0,0,0.0,3.0,3.0,Caucasian,F,1,Medium,7
7174,10586,Male,47.0,564.0,Greater than 45,0,0.0,0,0.0,3.0,3.0,African-American,M,1,Medium,5
7200,1665,Male,34.0,408.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,M,0,Medium,6

In [116]:
df.drop_duplicates()

,id,sex,age,age_in_months,age_cat,juv_misd_count,juv_fel_count,juv_other_count,juvenile_total,prior_offenses,priors_count,race,c_charge_degree,two_year_recid,score_text,decile_score
0,8423,Male,27.0,324.0,25 - 45,0,0.0,1,1.0,0.0,0.0,African-American,F,0,Low,2
1,4137,Male,23.0,276.0,Less than 25,0,0.0,0,0.0,3.0,3.0,Caucasian,M,1,High,8
2,5064,Male,28.0,336.0,25 - 45,0,0.0,0,0.0,2.0,2.0,Caucasian,F,1,Low,2
3,56,Female,21.0,252.0,Less than 25,0,NaN,0,0.0,2.0,2.0,African-American,F,0,High,8
4,9369,Male,31.0,372.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,M,0,Low,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7281,1685,Male,24.0,288.0,Less than 25,0,0.0,0,0.0,0.0,0.0,Hispanic,F,1,Medium,6
7282,616,Male,32.0,384.0,25 - 45,0,0.0,0,0.0,3.0,3.0,African-American,F,0,Low,2
7283,5394,Male,56.0,672.0,Greater than 45,0,0.0,0,0.0,3.0,3.0,NaN,F,0,Low,2
7284,2422,Male,27.0,324.0,25 - 45,0,0.0,0,0.0,1.0,1.0,African-American,F,0,Low,2
7285,8606,Male,24.0,288.0,Less than 25,0,0.0,0,0.0,0.0,0.0,African-American,NaN,1,Medium,7